apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: default
  labels:
    sticker: adidas
spec:
  containers:
  - name: nginx-container
    image: nginx 
    ports:
      - containerPort: 80
    
